# Generated by Django 3.2.5 on 2021-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_diary_diet_usercare'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary_diet',
            name='image',
            field=models.ImageField(blank=True, upload_to='D:\\python練習\\大二下暑假課程\\第二周\\PuYuan\x08ody_%Y-%m-%d_%H:%M:%S'),
        ),
    ]
