# Generated by Django 3.2.5 on 2021-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('relation_id', models.CharField(blank=True, max_length=100)),
                ('friend_type', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('read', models.BooleanField(blank=True, default=False)),
                ('imread', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
