# Generated by Django 3.2.5 on 2021-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('account', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fb_id', models.CharField(blank=True, max_length=100)),
                ('invite_code', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('emailck', models.BooleanField(default=True)),
                ('FBck', models.BooleanField(default=True)),
            ],
        ),
    ]
