# Generated by Django 3.2.5 on 2021-07-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='deflat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('sugar_dalta_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_delta_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_morning_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_morning_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_evening_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_evening_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_before_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_before_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_after_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('sugar_after_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('systolic_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('systolic_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('diastolic_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('diastolic_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('pulse_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('pulse_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('weight_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('weight_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('bmi_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('bmi_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('body_fat_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('body_fat_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
