# Generated by Django 3.2.5 on 2021-07-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210729_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('fcm_id', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=16, max_digits=19, null=True)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pushed_at', models.DateTimeField(auto_now=True)),
                ('unread_records_one', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('unread_records_two', models.CharField(blank=True, default='0', max_length=100)),
                ('unread_records_three', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('verified', models.CharField(default='0', max_length=10)),
                ('privacy_policy', models.CharField(default='0', max_length=10)),
                ('must_change_password', models.BooleanField(default=False)),
                ('status', models.CharField(default='Normal', max_length=100)),
                ('login_times', models.DecimalField(decimal_places=0, default='0', max_digits=15)),
                ('after_recording', models.CharField(default='0', max_length=1)),
                ('no_recording_for_a_day', models.CharField(default='0', max_length=1)),
                ('over_max_or_under_min', models.CharField(default='0', max_length=1)),
                ('after_mael', models.CharField(default='0', max_length=1)),
                ('unit_of_sugar', models.CharField(default='0', max_length=1)),
                ('unit_of_weight', models.CharField(default='0', max_length=1)),
                ('unit_of_height', models.CharField(default='0', max_length=1)),
                ('badge', models.DecimalField(decimal_places=0, default='0', max_digits=15)),
                ('group', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
