# Generated by Django 3.2.5 on 2021-08-01 09:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_druginformation_hba1c_medicalinformation_notification_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deflat',
            name='uid',
            field=models.UUIDField(default=uuid.uuid5, unique=True),
        ),
        migrations.AlterField(
            model_name='userset',
            name='uid',
            field=models.UUIDField(default=uuid.uuid5, unique=True),
        ),
    ]
