# Generated by Django 3.2.5 on 2021-08-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210801_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deflat',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userset',
            name='uid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
