# Generated by Django 3.2.5 on 2021-08-02 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210801_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deflat',
            old_name='sugar_dalta_max',
            new_name='sugar_delta_max',
        ),
    ]
