# Generated by Django 3.2.5 on 2021-08-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rename_sugar_dalta_max_deflat_sugar_delta_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deflat',
            name='bmi_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='bmi_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='body_fat_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='body_fat_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='diastolic_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='diastolic_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='pulse_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='pulse_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_after_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_after_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_before_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_before_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_delta_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_delta_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_evening_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_evening_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_morning_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='sugar_morning_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='systolic_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='systolic_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='weight_max',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='deflat',
            name='weight_min',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True),
        ),
    ]
